### ISSUE TITLE
Sketch of an object model

### ISSUE THREAD

**Issue by goiaba** [NorthBridge/playbook#25]

**Comment by goiaba** [comment]
I'm not sure if this structure fits well when developing with python. I'm also not sure if a service layer above dao layer would be a good idea. Actually, I hope you both can criticize this class diagram, because I'm not really happy with it.

Considering a service layer, our model layer would be like a thin model, it would work as a simple container of information without business logic. I always get confused about which is the best approach. Maybe you both can help me get rid of this doubt.

![playbook_milestone](https://cloud.githubusercontent.com/assets/1634735/7984169/592ef0da-0a9d-11e5-8320-37f650238240.jpg)

**Comment by kdflint** [comment]
Excellent work Bruno. You understand the essential components, for sure.

As we talked, I suggest putting your Helper components right inside
Milestone. This will answer your doubts about having such a thin model
class. Conceptually, a Milestone will know all about itself, including how
to create itself (in GitHub)

Sometimes when interacting with a database, you do have a separate service
layer. In future we may want to create a BacklogDAO base class that our
MilestoneDAO inherits (and probably IssueDAO too). BacklogDAO will
basically hold knowledge about connecting to the database.

For now you could just dump this knowledge into MilestoneDAO and abstract
it later.

Probably BacklogDAO will consume on an environment-specific config file
from which it reads database credentials at run time.

I don't think our system is complicated enough to warrant a full-blown
service layer. That's usually done when you want to completely abstract
your data source away from your app, by means of an API or something like
that.

Kathy


On Thu, Jun 4, 2015 at 7:55 AM, Bruno Godoy Martins Correa <
notifications@github.com> wrote:

> I'm not sure if this structure fits well when developing with python. I'm
> also not sure if a service layer above dao layer would be a good idea.
> Actually, I hope you both can criticize this class diagram, because I'm not
> really happy with it.
>
> Considering a service layer, our model layer would be like a thin model,
> it would work as a simple container of information without business logic.
> I always get confused about which is the best approach. Maybe you both can
> help me get rid of this doubt.
>
> [image: playbook_milestone]
> <https://cloud.githubusercontent.com/assets/1634735/7984169/592ef0da-0a9d-11e5-8320-37f650238240.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NorthBridge/playbook/issues/25#issuecomment-108884299>
> .
>



-- 
-- 



*Kathy Flint, CEO Northbridge Technology Alliance
http://northbridgetech.org
<http://NorthBridgeTech.org>kathy.flint@northbridgetech.org
<kathy.flint@northbridgetech.org> *

**Comment by goiaba** [comment]
Ok, I've changed the diagram. Tell me what do you think about it.

![playbook_milestone 1](https://cloud.githubusercontent.com/assets/1634735/8007436/2986bc98-0b72-11e5-9203-0170da069b6c.jpg)

Thanks,
Bruno.

**Comment by kdflint** [comment]
Bruno, I think this is perfectly adequate for our needs. Well considered.

On Fri, Jun 5, 2015 at 9:03 AM, Bruno Godoy Martins Correa <
notifications@github.com> wrote:

> Ok, I've changed the diagram. Tell me what do you think about it.
>
> [image: playbook_milestone 1]
> <https://cloud.githubusercontent.com/assets/1634735/8007436/2986bc98-0b72-11e5-9203-0170da069b6c.jpg>
>
> Thanks,
> Bruno.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NorthBridge/playbook/issues/25#issuecomment-109303436>
> .
>



-- 
-- 



*Kathy Flint, CEO Northbridge Technology Alliance
http://northbridgetech.org
<http://NorthBridgeTech.org>kathy.flint@northbridgetech.org
<kathy.flint@northbridgetech.org> *
