### ISSUE TITLE
Whitespace & naming conventions

### ISSUE THREAD

**Issue by hectron** [NorthBridge/playbook#26]
Good job on wiring up the DAOs! They look functional and simple. The only thing that I found strange was that there was a lot of trailing whitespace across the DAOs and the models. Can this be cleaned up?

The models look good, but readability might be easier for others if the methods were `snake_cased`. An example would be `Milestone`'s `getID` method. This is more readable if it were written `get_id`. 

A few other methods have `camelCase` and would be easier to understand if they were `snake_cased`.

Good job so far!

**Comment by goiaba** [comment]
Hector, thanks for your tips. That was what I was looking for. I've never worked with python, so I brought some 'addictions' from the language I used to work with.

Ok, could you clarify me about the "trailing whitespace across the DAOs and the model"?

I'll work on changing the method's names. Actually, I've already started after start reading a book Blake suggested me (Fluent Python). So now I must go back and fix the past work.

Thanks again.

**Comment by hectron** [comment]
Hey @goiaba , I think that you're doing pretty well for not working with Python but now I'm curious about what programming languages have you worked with.

Here is a screenshot that I took from Vim. I have an extension called [Vim Better Whitespace](https://github.com/ntpeters/vim-better-whitespace) which highlights any empty spaces:

![image](https://cloud.githubusercontent.com/assets/1649281/8379288/9aa44ada-1be4-11e5-8ceb-b14ce336fd51.png)

**Comment by goiaba** [comment]
@hectron, I used to work with Java. Recently, after coming to Chicago, I was introduced to Scala and loved it. But to be honest, I do not have much professional experience with either one. When I say "work with" actually it means take courses and study at home. Before leaving Brazil I was working with server infrastructure not development (sometimes we have no choice).

Thanks for the screenshot, now I know what you are talking about. :-) I will clean the code up and also install this plugin.

**Comment by martsberger** [comment]
Along with what @hectron is bringing up regarding whitespace, what IDE are you using and can you look into whether or not it supports a python linter? The linter will tell you about any PEP8 violations you have and also catch other issues like calling methods with the wrong arguments. Since you are used to working with Java, you are used to the compiler catching that kind of error for you, but with Python it won't be caught until run time unless you use a linter.

**Comment by foresmac** [comment]
For instance, in our office most of us use [SublimeText](http://www.sublimetext.com) (versions for OS X, Win, and Linux) with [SublimerLinter](http://www.sublimelinter.com/en/latest/) package installed.

**Comment by goiaba** [comment]
@martsberger, I was using LiClipse and I enabled the linter after your message. But now that @foresmac mentioned Sublime, I think it would be nice try this tool. It was already installed in my machine but I've never used before. Today I installed these packages on my Sublime: Python PEP8 Autoformat, AutoPEP8, Python Pep8 Lint and SublimeLinter.

**Comment by jwegner89** [comment]
I also really like PyCharm as an IDE for Python. It automatically does linting and PEP8 enforcement, as well as easy integration with version control. I also like that it has a vi plugin, as that is my editor of choice.

**Comment by goiaba** [comment]
Thank you guys for the tips. I'm now using sublime with sublimerlinter and trying to follow python naming conventions.
