### ISSUE TITLE
A neat suggestion

### ISSUE THREAD

**Issue by hectron** [NorthBridge/playbook#27]
I think it might be helpful if there was an extension to the `utils.configHelper`. If there was a way to pass any number of arguments and have it return the keys from the config file.

E.g.

`database, host, user, password = get_configuration_values('database.name', 'database.host', 'database.user', 'database.password')`

Do you think that this might be useful?

**Comment by goiaba** [comment]
It would probably be very useful. Less repetition over the code. Great.

**Comment by goiaba** [comment]
Hi @hectron, I've created this method, but now both of them are useless, because we are using django settings files instead of json files. But thanks for the clue, it was helpful.
