### ISSUE TITLE
Python getters and setters

### ISSUE THREAD

**Issue by martsberger** [NorthBridge/playbook#28]
This is part of the transition from Java to Python, my opinion is that it's not necessary to keep all your class attributes private with a layer of getters and setters over them. It's a layer of code reduces the clarity of the design.

That said, if you do keep the private attribute getter/setter pattern, python has a built in way of handling getters and setters, http://stackoverflow.com/questions/6618002/python-property-versus-getters-and-setters.

**Comment by goiaba** [comment]
@martsberger, we are now using django and I removed all the getters/setters. Thanks for alerting me.
