### ISSUE TITLE
Using positional args in addition to **kwargs

### ISSUE THREAD

**Issue by martsberger** [NorthBridge/playbook#29]
In the issue class you have (simplified for clarity):

```python
class Issue():
    def __init__(self, **kwargs):
        self.__title = kwargs.get('title', None)
        # Other assignments

    def create_data(self):
        if self.__title is None:
            log.error('...')
            raise RuntimeError('...')
        data = {'title': self.__title}
        # etc.
```

I would consider making `title` a required field for initializing an Issue. The benefits are that you don't have to check for it and raise an exception in the create_data method, If the programmer does try to instantiate an Issue without a title, they will get a stacktrace with their error in it (unlike currently, where the exception isn't raised near the programming error), and your linter can catch the mistake before runtime.

```python
class Issue():
    def __init__(self, title, **kwargs):
        self.__title = title
        # Other assignments

    def create_data(self):
        data = {'title': self.__title}
        # etc.
```

**Comment by goiaba** [comment]
@martsberger, this class does not exist anymore, because of our migration to django, but I got your point and it makes a lot of sense. Thanks.

**Comment by foresmac** [comment]
If you're using Django and need an API, I highly recommend [Django REST Framework](http://www.django-rest-framework.org).
