### ISSUE TITLE
configuring postgres

### ISSUE THREAD

**Issue by rebeldroid12** [NorthBridge/playbook#37]
The database settings are located in the playbook/settings.py file and must be updated to represent your local environment. There is also two other files that must be updated: playbook/email_settings.py (information concerning email service) and playbook/backlog/github_settings.py (information used to interact with the github API)

install postgres:

https://help.ubuntu.com/community/PostgreSQL

create database northbr6_devwaterwheel

can change user to fit file aka user: postgres with password postgres OR configure to have your username and password. for former: 

In a terminal, type:

sudo -u postgres psql postgres
Set a password for the "postgres" database role using the command:

\password postgres

**Comment by goiaba** [comment]
README file updated.

**Comment by goiaba** [comment]
README file updated.
