### ISSUE TITLE
issue at step: python manage.py makemigrations

### ISSUE THREAD

**Issue by rebeldroid12** [NorthBridge/playbook#39]
error message:

You are trying to add a non-nullable field 'project' to backlog without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows)
 2) Quit, and let me add a default in models.py
Select an option:

**Comment by goiaba** [comment]
Done (commit 9174e846ee856e464b2b3977c8279bc149d541c9)
